on:
  release:
    types: [published, edited]
name: nori-plugin-builder
env:
  PLUGIN_NAME: authentication
jobs:
  build-plugins:
    name: build-plugin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux", "darwin", "freebsd"]
        arch: ["386", "amd64"]
    steps:
      - name: Set up Go 1.15.6
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6
      - name: Check out code into the Go module directory
        id: check
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build --buildmode=plugin -o plugin.so ./../authentication2/plugin/main.go
      - name: Upload production artifacts
        uses: actions/upload-artifact@v2
        with:
          path: plugin.so
      - name: Display structure uploaded files
        run: ls -R
      - name: Download production artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/plugin.so
          asset_name: ${{ env.PLUGIN_NAME }}_${{ matrix.os }}_${{ matrix.arch }}.so
          tag: ${{ github.ref }}
          overwrite: true
