name: 'Build Nori Plugin'
description: 'Build Nori plugin'
author: 'Nori'
runs:
  using: "composite"
  steps: 
    - run: ls -R
      shell: bash
    - run: sh ${{ github.action_path }}/script.sh
      shell: bash

