name: 'Build Nori Plugin'
description: 'Build Nori plugin'
author: 'Nori'
inputs:
  pluginName:
    description: 'name of plugin'
    required: false
    default: 'plugin'
runs:
  using: "composite"
  steps: 
    - run: pwd
      shell: bash
    - run: sh ${{ github.action_path }}/script.sh
      shell: bash
      args:
      - ${{ inputs.pluginName}}

